//! String/memory operations — Rusl implementation of libc string functions.
//! Auto-generated from spec files.

#![allow(dead_code, unused_imports)]

mod bcmp;
mod bcopy;
mod bzero;
mod explicit_bzero;
mod index;
mod memccpy;
mod memchr;
mod memcmp;
mod memcpy;
mod memmem;
mod memmove;
mod mempcpy;
mod memrchr;
mod memset;
mod rindex;
mod stpcpy;
mod stpncpy;
mod strcasecmp;
mod strcasestr;
mod strcat;
mod strchr;
mod strchrnul;
mod strcmp;
mod strcpy;
mod strcspn;
mod strdup;
mod strerror_r;
mod strlcat;
mod strlcpy;
mod strlen;
mod strncasecmp;
mod strncat;
mod strncmp;
mod strncpy;
mod strndup;
mod strnlen;
mod strpbrk;
mod strrchr;
mod strsep;
mod strsignal;
mod strspn;
mod strstr;
mod strtok;
mod strtok_r;
mod strverscmp;
mod swab;
mod wcpcpy;
mod wcpncpy;
mod wcscasecmp;
mod wcscasecmp_l;
mod wcscat;
mod wcschr;
mod wcscmp;
mod wcscpy;
mod wcscspn;
mod wcsdup;
mod wcslen;
mod wcsncasecmp;
mod wcsncasecmp_l;
mod wcsncat;
mod wcsncmp;
mod wcsncpy;
mod wcsnlen;
mod wcspbrk;
mod wcsrchr;
mod wcsspn;
mod wcsstr;
mod wcstok;
mod wcswcs;
mod wmemchr;
mod wmemcmp;
mod wmemcpy;
mod wmemmove;
mod wmemset;

pub use bcmp::{bcmp};
pub use bcopy::{bcopy};
pub use bzero::{bzero};
pub use explicit_bzero::{explicit_bzero};
pub use index::{index};
pub use memccpy::{memccpy};
pub use memchr::{memchr};
pub use memcmp::{memcmp};
pub use memcpy::{memcpy};
pub use memmem::{memmem};
pub use memmove::{memmove};
pub use mempcpy::{mempcpy};
pub use memrchr::{memrchr};
pub use memset::{memset};
pub use rindex::{rindex};
pub use stpcpy::{stpcpy};
pub use stpncpy::{stpncpy};
pub use strcasecmp::{strcasecmp};
pub use strcasestr::{strcasestr};
pub use strcat::{strcat};
pub use strchr::{strchr};
pub use strchrnul::{strchrnul};
pub use strcmp::{strcmp};
pub use strcpy::{strcpy};
pub use strcspn::{strcspn};
pub use strdup::{strdup};
pub use strerror_r::{strerror_r};
pub use strlcat::{strlcat};
pub use strlcpy::{strlcpy};
pub use strlen::{strlen};
pub use strncasecmp::{strncasecmp};
pub use strncat::{strncat};
pub use strncmp::{strncmp};
pub use strncpy::{strncpy};
pub use strndup::{strndup};
pub use strnlen::{strnlen};
pub use strpbrk::{strpbrk};
pub use strrchr::{strrchr};
pub use strsep::{strsep};
pub use strsignal::{strsignal};
pub use strspn::{strspn};
pub use strstr::{strstr};
pub use strtok::{strtok};
pub use strtok_r::{strtok_r};
pub use strverscmp::{strverscmp};
pub use swab::{swab};
pub use wcpcpy::{wcpcpy};
pub use wcpncpy::{wcpncpy};
pub use wcscasecmp::{wcscasecmp};
pub use wcscasecmp_l::{wcscasecmp_l};
pub use wcscat::{wcscat};
pub use wcschr::{wcschr};
pub use wcscmp::{wcscmp};
pub use wcscpy::{wcscpy};
pub use wcscspn::{wcscspn};
pub use wcsdup::{wcsdup};
pub use wcslen::{wcslen};
pub use wcsncasecmp::{wcsncasecmp};
pub use wcsncasecmp_l::{wcsncasecmp_l};
pub use wcsncat::{wcsncat};
pub use wcsncmp::{wcsncmp};
pub use wcsncpy::{wcsncpy};
pub use wcsnlen::{wcsnlen};
pub use wcspbrk::{wcspbrk};
pub use wcsrchr::{wcsrchr};
pub use wcsspn::{wcsspn};
pub use wcsstr::{wcsstr};
pub use wcstok::{wcstok};
pub use wcswcs::{wcswcs};
pub use wmemchr::{wmemchr};
pub use wmemcmp::{wmemcmp};
pub use wmemcpy::{wmemcpy};
pub use wmemmove::{wmemmove};
pub use wmemset::{wmemset};

pub use rusl_core::test;